AWSTemplateFormatVersion: 2010-09-09
Description: AutoScalingGroup

Resources: 

  LC1:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: LC1
      ImageId: ami-07d9160fa81ccffb5
      InstanceType: t2.micro
      KeyName: Udemy
      SecurityGroups: 
        - sg-0af72a3187a6470ca
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo su
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          cd /var/www/html
          echo “This is a test page running on Apache on EC2 in the AWS Cloud from $(hostname -f)” > index.html
          sudo amazon-linux-extras install epel -y
          sudo yum install stress -y

  ASG1:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LC1
    Properties:
      AutoScalingGroupName: ASG1
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: LC1
      HealthCheckGracePeriod : 300 
      DesiredCapacity: 3
      MaxSize: 6
      MinSize: 2
      Tags:
        - Key: Name
          Value: ASG1 Instances
          PropagateAtLaunch: True

  CPUUTIL:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn: ASG1
    Properties:
      AutoScalingGroupName: ASG1
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50